server:
  port: 8080

# spring配置
web.upload-path: D:/images
spring:
  resources:
    static-locations: classpath:/,classpath:/themes/,file:${web.upload-path}
  devtools:
    restart:
      enabled: false
  freemarker:
    template-loader-path: classpath:/
    charset: UTF-8
    suffix: .ftl
    content-type: text/html; charset=utf-8
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/perfree?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 215607..
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000
      filter:
        stat:
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 2000
        config:
          enabled: true
        wall:
          enabled: true
          db-type: mysql
          config:
            delete-allow: true
            drop-table-allow: true
            multi-statement-allow: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.perfree.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#pagehelper配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql