server:
  port: 8081

# spring配置
web.upload-path: resources/upload/
spring:
  devtools:
    restart:
      enabled: false
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  datasource:
    url: jdbc:mysql://196.196.16.2:3306/perfree?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 215607..
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000
      filter:
        stat:
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 2000
        config:
          enabled: true
        wall:
          enabled: true
          db-type: mysql
          config:
            delete-allow: true
            drop-table-allow: true
            multi-statement-allow: true
  mvc:
    view:
      prefix: /
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.perfree.model

#pagehelper配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

logging:
  level:
    com.perfree: info
  file:
    name: ./logs/Perfree.log
    max-history: 7
    max-size: 10MB
cache:
  ehcache:
    config: ehcache.xml