server:
  # 端口
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/javascript,text/css
    min-response-size: 2048

version: 1.2.4
# 默认文件上传地址
web.upload-path: resources/upload/
spring:
  aop:
    proxy-target-class: true
  devtools:
    restart:
      enabled: false
  servlet:
    multipart:
      # 单个文件上传允许最大大小,默认-1为不限制,如需限制大小改为具体的大小即可,如100MB
      max-file-size: -1
      # 总上传的数据大小,默认-1为不限制,如需限制大小改为具体的大小即可,如100MB
      max-request-size: -1
  datasource:
    url: jdbc:mysql://196.196.16.2:3306/perfree?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 215607..
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000
      filter:
        stat:
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 2000
        config:
          enabled: true
        wall:
          enabled: true
          db-type: mysql
          config:
            delete-allow: true
            drop-table-allow: true
            multi-statement-allow: true
  mvc:
    view:
      prefix: /
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.perfree.model

#pagehelper配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

logging:
  level:
    com.perfree: error
    com.perfree.config.PostAppRunner: info
    com.perfree.Application: info
    com.perfree.plugins: info
  file:
    name: ./logs/Perfree.log
    max-history: 7
    max-size: 10MB
cache:
  ehcache:
    config: ehcache.xml